import Grass.Process.Trace.Independence

/-!
# What the observation trace can and cannot witness

`docs/PROCESS.md` §7 asks for the graph-level result the flattening and
serial-scheduler theorems consume:

> The trace congruence is generated by adjacent independent swaps (a nominal
> partial-order/Mazurkiewicz trace), preserving dependent result and occurrence
> identity through each transport.

`Grass/Process/Trace/Independence.lean` says when two steps are independent and
names the diamond as an obligation rather than assuming it. This module is the
other half: what the *trace* does across a schedule, which turns out to be
answerable without the diamond.

## The two theorems that matter

**The trace only grows.** `observations_extend` is by cases over all
constructors of `NetworkTransition`, and it is the reason a
specification stated over observations is stable under execution: no step
rewrites or truncates the trace, so an observation a specification demanded
cannot be dropped by a later step. Twenty-one constructors get it from
`touchesOnly` — they do not scope the trace at all — and the two that do,
`processStep` and `commit`, carry an append equation as a field.

**Two independent steps cannot both emit.** `independent_steps_do_not_both_emit`
is a one-line consequence of both emitting constructors declaring
`.observations` in their scope while `Independent` is scope disjointness. So of
any two independent steps, at least one leaves the trace exactly as it found it,
and swapping them cannot reorder two emissions because there are never two to
reorder.

**This is a narrowing, not a strengthening, and the difference matters.** A
first draft of this module reported it as making §7's
`BoundaryObservationsCommute` "contentless", which local adversarial review
rejected: §7 asks for a congruence under which reordering independent steps
preserves the observed trace, and this layer obtains it by making every pair
that could reorder two emissions non-independent. The obligation has been moved,
not discharged — a plan that wants two subsystems to emit concurrently needs a
per-subsystem trace or an explicit commutation argument, and neither exists
here. It is recorded in `docs/PROCESS_IMPLEMENTATION_PLAN.md` §10.27.

What the same review *did* fix is worse and is now gone: `StepsLocally` used to
declare `.observations` unconditionally, so two local steps on unrelated
instances that emitted nothing were never independent either. The guard is now
`emitted ≠ []`, and `emits_iff_the_trace_moved` is the check — `Emits` holds
exactly when the trace actually moved, not when the constructor might have moved
it.

## What is still owed, and where

The constructive diamond stays where `Independence.lean` left it, and it is not
the only thing owed. §7 names, and nothing in this corpus yet states:

* `independent_diamond` — the swap itself, named as `SwapsWith` in
  `Independence.lean` and discharged nowhere;
* `syscall_linearizations_equivalent` and `StrongObservedExecutionEquivalence` —
  there is no syscall, no linearization and no partial order in this module, and
  `docs/PROCESS_IMPLEMENTATION_PLAN.md` assigns this file "syscall partial
  orders";
* `TraceRelatedBySwap` — the trace congruence as an object, rather than the two
  facts about it proved here;
* `ProviderEffectsCommute` — provider operation footprints, handle identities
  and interruption laws, none of which this layer has;
* `NetworkWorldEquivalent` — equality is used throughout instead;
* `CompatibleSharedAccess` — §7's relation is *compatible*, which is wider than
  the disjointness of written regions `Independent` uses.

`BoundaryObservationsCommute` is the only §7 name this module engages, and see
above for how.
-/

namespace Grass.Process

open Grass.Specification

universe u w v r m o

namespace ProcessPlan

variable {registry : ProtocolRegistry.{u, w, v}} {boundary : DriverBoundary.{u}}
  {Obligations : Type o} {plan : ProcessPlan.{u, w, v, r, m, o} registry boundary Obligations}

/-! ## Who may write the trace -/

/--
A step that appends to the observation trace.

Not a new field: it is `.observations` being in the step's declared scope. Since
both emitting constructors guard that on their segment being non-empty,
`emits_iff_the_trace_moved` below makes this exact rather than an
over-approximation — `Emits` holds precisely when the trace actually moved.
-/
def NetworkTransition.Emits {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) : Prop :=
  transition.scope .observations

/--
A step that did not declare the trace left it exactly.

Immediate from `touchesOnly`, and the half of the argument that covers
all but two of the constructors.
-/
theorem trace_unchanged_of_silent {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) (silent : ¬ transition.Emits) :
    before.observations = after.observations :=
  transition.touchesOnly .observations silent

/--
**The observation trace only ever grows.**

`docs/PROCESS.md` §6 says a commit "appends to the observation trace", and this
is what that is worth once the whole transition family is in view: *no* step
rewrites or truncates it. A specification stated over observations is therefore
stable under execution — an observation it demanded cannot be dropped by a later
step, whatever that step was.

The proof is a case split on whether the step declared the trace at all. If it
did not, `touchesOnly` gives equality. If it did, it is one of exactly two
constructors, and each carries the append equation as a field: `processStep`'s
`observationsExtend` and `commit`'s `appended`.

Worth noting what would have gone wrong without the scope discipline. There is
nothing in `LogicalProcessNetworkCore` that stops a transition from setting
`observations` to `[]`; what stops it is that such a step would have to declare
`.observations` in its scope, and then it would have to be one of these two
constructors, and both of them append.
-/
theorem observations_extend {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    ∃ emitted, after.observations = before.observations ++ emitted := by
  by_cases emits : transition.Emits
  · cases transition with
    | processStep _ _ _ emitted _ _ step => exact ⟨emitted, step.observationsExtend⟩
    | commit emitted step => exact ⟨emitted, step.appended⟩
    | _ => exact absurd emits (by simp [NetworkTransition.Emits, NetworkTransition.scope])
  · exact ⟨[], by rw [← trace_unchanged_of_silent transition emits, List.append_nil]⟩

/--
**A step emits exactly when the trace moved.**

Both directions are content. Backward is `trace_unchanged_of_silent`
contraposed: a step cannot change the trace without declaring it, which is the
scope discipline. Forward is the `emitted ≠ []` guard on the two emitting
constructors: a step that declares the trace really did append something to it.

Without the guard the forward direction is false — a `processStep` with an empty
segment would declare the trace and move nothing — and `Emits` would be a
*may-emit* predicate wearing an emit predicate's name. That is what an earlier
draft had, and what made every pair of local steps non-independent.
-/
theorem emits_iff_the_trace_moved {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    transition.Emits ↔ before.observations ≠ after.observations := by
  constructor
  · intro emits
    cases transition with
    | processStep _ _ _ emitted _ _ step =>
      rcases emits with isSlot | ⟨nonempty, _⟩ | ⟨_, _, isRegion⟩
      · exact absurd isSlot (by simp)
      · intro same
        have lengths := congrArg List.length step.observationsExtend
        rw [← same, List.length_append] at lengths
        have : emitted.length = 0 := by omega
        exact nonempty (List.eq_nil_of_length_eq_zero this)
      · exact absurd isRegion (by simp)
    | commit emitted step =>
      obtain ⟨nonempty, _⟩ := emits
      intro same
      have lengths := congrArg List.length step.appended
      rw [← same, List.length_append] at lengths
      have : emitted.length = 0 := by omega
      exact nonempty (List.eq_nil_of_length_eq_zero this)
    | _ => exact absurd emits (by simp [NetworkTransition.Emits, NetworkTransition.scope])
  · intro moved
    exact Classical.byContradiction
      (fun silent => moved (trace_unchanged_of_silent transition silent))

/-- So the trace before a step is a prefix of the trace after it. -/
theorem observations_prefix {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    before.observations <+: after.observations := by
  obtain ⟨emitted, appended⟩ := observations_extend transition
  exact ⟨emitted, appended.symm⟩

/-- And across a whole execution, by the same argument. -/
theorem execution_observations_extend {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    ∃ emitted, after.observations = before.observations ++ emitted := by
  induction execution with
  | still => exact ⟨[], (List.append_nil _).symm⟩
  | more _ step ih =>
    obtain ⟨earlier, upToHere⟩ := ih
    obtain ⟨segment, lastStep⟩ := observations_extend step.transition
    exact ⟨earlier ++ segment, by rw [lastStep, upToHere, List.append_assoc]⟩

/--
**No execution retracts an observation.**

The form a specification consumes: whatever the schedule did, everything
observed so far is still observed. `docs/FOUNDATION.md` law 7 at the trace — an
obligation discharged by emitting an observation cannot be undischarged by a
later step.
-/
theorem execution_observations_prefix {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    before.observations <+: after.observations := by
  obtain ⟨emitted, appended⟩ := execution_observations_extend execution
  exact ⟨emitted, appended.symm⟩

/-! ## What independence buys at the trace -/

/--
**Two independent steps cannot both emit.**

The Mazurkiewicz content of `docs/PROCESS.md` §7, and it costs one line because
of a fact nothing arranged for it: both emitting constructors declare
`.observations` in their scope, and `NetworkTransition.Independent` is scope
disjointness.

So a swap of two independent steps cannot reorder two emissions — there are
never two emissions to reorder. §7's `BoundaryObservationsCommute` has no
content to prove at this layer, which is a stronger outcome than proving it.
-/
theorem independent_steps_do_not_both_emit
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right) : ¬ (left.Emits ∧ right.Emits) :=
  fun both => independent .observations both.1 both.2

/--
**So one of any two independent steps leaves the trace exactly.**

The usable form: whichever way the scheduler ran them, at most one contributed,
and the other's endpoints agree on the trace.
-/
theorem one_of_two_independent_steps_is_silent
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right) :
    a.observations = b.observations ∨ c.observations = d.observations := by
  by_cases emits : left.Emits
  · exact Or.inr (trace_unchanged_of_silent right
      (fun inRight => independent .observations emits inRight))
  · exact Or.inl (trace_unchanged_of_silent left emits)

/--
**An emission is attributable to one step.**

If a step emitted anything at all, every step independent of it emitted nothing.
That is what makes a trace segment a fact about *which* step ran rather than
about the schedule: two independent steps never compete for a position in the
trace.
-/
theorem emission_is_attributable
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right)
    (emitted : a.observations ≠ b.observations) :
    c.observations = d.observations := by
  refine trace_unchanged_of_silent right (fun inRight => ?_)
  refine emitted (trace_unchanged_of_silent left (fun inLeft => ?_))
  exact independent .observations inLeft inRight

/--
**A swap moves the emission from one side of the schedule to the other, and
changes nothing else about the trace.**

Both orders run two independent steps, so in each order one of them is silent
and the intermediate state's trace is either the start's or the end's. There is
no third possibility, and in particular no order in which the trace is built up
in two pieces — which is what a commutation argument about observation segments
would have had to rule out, and what
`independent_steps_do_not_both_emit` rules out instead.

The swap is what supplies the reordered execution's intermediate state, and the
existential carries the two reordered *steps* and their scope equations so that
`middle` is pinned to the swap's own witness. That matters: a version whose
existential mentioned only `middle` is satisfied by `⟨first, Or.inl rfl⟩` with
no independence, no swap and no steps at all. Two earlier drafts were vacuous in
two different ways — the first took the swap hypothesis and never used it, and
the second destructured it but concluded something the swap did not bound. Local
adversarial review found both.
-/
theorem a_swap_only_moves_the_emission
    {first second third : plan.LogicalProcessNetwork}
    {left : plan.NetworkStep first second} {right : plan.NetworkStep second third}
    (independent : left.transition.Independent right.transition)
    (swap : SwapsWith left right) :
    (first.observations = second.observations ∨ second.observations = third.observations) ∧
      ∃ (middle : plan.LogicalProcessNetwork)
        (swappedRight : plan.NetworkStep first middle)
        (swappedLeft : plan.NetworkStep middle third),
        (∀ fragment, swappedRight.transition.scope fragment ↔ right.transition.scope fragment) ∧
        (∀ fragment, swappedLeft.transition.scope fragment ↔ left.transition.scope fragment) ∧
        (first.observations = middle.observations ∨
          middle.observations = third.observations) := by
  refine ⟨one_of_two_independent_steps_is_silent independent, ?_⟩
  obtain ⟨middle, swappedRight, swappedLeft, rightScope, leftScope⟩ := swap
  refine ⟨middle, swappedRight, swappedLeft, rightScope, leftScope, ?_⟩
  refine one_of_two_independent_steps_is_silent (left := swappedRight.transition)
    (right := swappedLeft.transition) ?_
  intro fragment inSwappedRight inSwappedLeft
  exact independent fragment ((leftScope fragment).mp inSwappedLeft)
    ((rightScope fragment).mp inSwappedRight)

end ProcessPlan

end Grass.Process
