import Grass.Process.Trace.Independence

/-!
# What the observation trace can and cannot witness

`docs/PROCESS.md` §7 asks for the graph-level result the flattening and
serial-scheduler theorems consume:

> The trace congruence is generated by adjacent independent swaps (a nominal
> partial-order/Mazurkiewicz trace), preserving dependent result and occurrence
> identity through each transport.

`Grass/Process/Trace/Independence.lean` says when two steps are independent and
names the diamond as an obligation rather than assuming it. This module is the
other half: what the *trace* does across a schedule, which turns out to be
answerable without the diamond.

## The two theorems that matter

**The committed trace only grows.** `observations_extend` is by cases over all
constructors of `NetworkTransition`, and it is the reason a specification stated
over observations is stable under execution: no step rewrites or truncates it, so
an observation a specification demanded cannot be dropped by a later step.
Twenty-three constructors get it from `touchesOnly` — they do not scope
`.observations` at all — and `commit`, the one that does, carries the append
equation as a field.

That case count changed when `NetworkFragment.pending` split the two traces.
`processStep`, `spawn` and `restart` used to append to `observations` directly,
which is what left `Commits` with nothing to be about; they now append to
`pending`, and only a commit publishes. The theorem is unchanged and its proof is
three cases shorter.

**Two independent steps cannot both emit.** `independent_steps_do_not_both_emit`
is a one-line consequence of every observation-touching constructor declaring
`.pending` in its scope while `Independent` is scope disjointness. `Emits` is
`.pending`-in-scope rather than `.observations`-in-scope, and it selects *more*
steps: `publishing_produces` is one-way containment, and a `processStep` that
produces without publishing is the gap. That is the right direction for law 18 —
the predicate has to catch every step that could compete for a position in a
trace — and an earlier version of this paragraph said the two "agree on which
steps they select", which is false and was checked by a reviewer against this
module's own `processStep` fixture. So of any two independent steps, at least one leaves both
traces exactly as it found them, and swapping them cannot reorder two emissions
because there are never two to reorder.

**This is a narrowing, not a strengthening, and the difference matters.** A
first draft of this module reported it as making §7's
`BoundaryObservationsCommute` "contentless", which local adversarial review
rejected: §7 asks for a congruence under which reordering independent steps
preserves the observed trace, and this layer obtains it by making every pair
that could reorder two emissions non-independent. The obligation has been moved,
not discharged — a plan that wants two subsystems to emit concurrently needs a
per-subsystem trace or an explicit commutation argument, and neither exists
here. It is recorded in `docs/PROCESS_IMPLEMENTATION_PLAN.md` §10.27.

What the same review *did* fix is worse and is now gone: `StepsLocally` used to
declare `.observations` unconditionally, so two local steps on unrelated
instances that emitted nothing were never independent either. The guard is now
`emitted ≠ []`, and `emits_iff_the_pending_trace_moved` is the check — `Emits`
holds exactly when a trace actually moved, not when the constructor might have
moved it.

## What is still owed, and where

The constructive diamond stays where `Independence.lean` left it, and it is not
the only thing owed. §7 names, and nothing in this corpus yet states:

* `independent_diamond` — the swap itself, named as `SwapsWith` in
  `Independence.lean` and discharged nowhere;
* `syscall_linearizations_equivalent` and `StrongObservedExecutionEquivalence` —
  there is no syscall, no linearization and no partial order in this module, and
  `docs/PROCESS_IMPLEMENTATION_PLAN.md` assigns this file "syscall partial
  orders";
* `TraceRelatedBySwap` — the trace congruence as an object, rather than the two
  facts about it proved here;
* `ProviderEffectsCommute` — provider operation footprints, handle identities
  and interruption laws, none of which this layer has;
* `NetworkWorldEquivalent` — equality is used throughout instead;
* `CompatibleSharedAccess` — §7's relation is *compatible*, which is wider than
  the disjointness of written regions `Independent` uses.

`BoundaryObservationsCommute` is the only §7 name this module engages, and see
above for how.
-/

namespace Grass.Process

open Grass.Specification

universe u w v r m o

namespace ProcessPlan

variable {registry : ProtocolRegistry.{u, w, v}} {boundary : DriverBoundary.{u}}
  {Obligations : Type o} {plan : ProcessPlan.{u, w, v, r, m, o} registry boundary Obligations}

/-! ## Who may write the trace -/

/--
A step that touches an observation trace — either by producing into `pending` or
by publishing from it.

Not a new field: it is `.pending` being in the step's declared scope. Every
constructor that appends to `observations` also declares `.pending`
(`publishing_produces`), because the only one is `commit` and a commit consumes
the pending prefix it publishes — so this single fragment selects exactly the
steps that could compete for a position in the trace, which is what law 18 needs.

Since every such constructor guards its scope on the segment being non-empty,
`emits_iff_the_pending_trace_moved` below makes this exact rather than an
over-approximation.
-/
def NetworkTransition.Emits {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) : Prop :=
  transition.scope .pending

/--
**Publishing implies producing.**

The containment that lets one fragment stand for both traces. `commit` is the
only constructor whose scope holds at `.observations`, and its scope is a
disjunction over the two trace fragments, so it holds at `.pending` too.
-/
theorem publishing_produces {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after)
    (publishes : transition.scope .observations) : transition.Emits := by
  cases transition with
  | commit _ _ => exact ⟨publishes.1, Or.inr rfl⟩
  | _ => exact absurd publishes (by simp [NetworkTransition.scope])

/--
A step that did not declare either trace left the committed one exactly.

Immediate from `touchesOnly` and `publishing_produces`, and the half of the
argument that covers all but one of the constructors.
-/
theorem trace_unchanged_of_silent {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) (silent : ¬ transition.Emits) :
    before.observations = after.observations :=
  transition.touchesOnly .observations
    (fun publishes => silent (publishing_produces transition publishes))

/--
**The observation trace only ever grows.**

`docs/PROCESS.md` §6 says a commit "appends to the observation trace", and this
is what that is worth once the whole transition family is in view: *no* step
rewrites or truncates it. A specification stated over observations is therefore
stable under execution — an observation it demanded cannot be dropped by a later
step, whatever that step was.

The proof is a case split on whether the step declared the committed trace at
all. If it did not, `touchesOnly` gives equality. If it did, it is `commit`, and
`Commits.appended` is the equation.

Worth noting what would have gone wrong without the scope discipline. There is
nothing in `LogicalProcessNetworkCore` that stops a transition from setting
`observations` to `[]`; what stops it is that such a step would have to declare
`.observations` in its scope, and then it would have to be `commit`, and a commit
appends.
-/
theorem observations_extend {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    ∃ emitted, after.observations = before.observations ++ emitted := by
  by_cases publishes : transition.scope (.observations : NetworkFragment plan.topology)
  · cases transition with
    | commit emitted step => exact ⟨emitted, step.appended⟩
    | _ => exact absurd publishes (by simp [NetworkTransition.scope])
  · refine ⟨[], ?_⟩
    rw [← transition.touchesOnly .observations publishes, List.append_nil]

/--
**A step that publishes moved the committed trace, and no other step did.**

Backward is `trace_unchanged_of_silent` contraposed: a step cannot change the
committed trace without declaring it, which is the scope discipline. Forward is
`Commits.nonempty`: the only publishing constructor really did append something.
-/
theorem publishes_iff_the_trace_moved {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    transition.scope (.observations : NetworkFragment plan.topology) ↔
      before.observations ≠ after.observations := by
  constructor
  · intro publishes
    cases transition with
    | commit emitted step =>
      obtain ⟨nonempty, _⟩ := publishes
      intro same
      have lengths := congrArg List.length step.appended
      rw [← same, List.length_append] at lengths
      exact nonempty (List.eq_nil_of_length_eq_zero (by omega))
    | _ => exact absurd publishes (by simp [NetworkTransition.scope])
  · intro moved
    exact Classical.byContradiction
      (fun silent => moved (transition.touchesOnly .observations silent))

/--
**And a step emits exactly when the pending trace moved.**

The `Emits` version, and the one law 18 uses. Forward is the `emitted ≠ []` guard
that every observation-touching constructor carries; backward is the scope
discipline again.

Without the guard the forward direction is false — a `processStep` with an empty
segment would declare the trace and move nothing — and `Emits` would be a
*may-emit* predicate wearing an emit predicate's name. That is what an earlier
draft had, and what made every pair of local steps non-independent.
-/
theorem emits_iff_the_pending_trace_moved {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    transition.Emits ↔ before.pending ≠ after.pending := by
  constructor
  · intro emits
    cases transition with
    | processStep _ _ _ emitted _ _ step =>
      rcases emits with isSlot | ⟨nonempty, _⟩ | ⟨_, _, isRegion⟩
      · exact absurd isSlot (by simp)
      · intro same
        have lengths := congrArg List.length step.producesPending
        rw [← same, List.length_append] at lengths
        exact nonempty (List.eq_nil_of_length_eq_zero (by omega))
      · exact absurd isRegion (by simp)
    | commit emitted step =>
      obtain ⟨nonempty, _⟩ := emits
      intro same
      have lengths := congrArg List.length step.earned
      rw [same, List.length_append] at lengths
      exact nonempty (List.eq_nil_of_length_eq_zero (by omega))
    | spawn _ _ _ emitted _ step =>
      rcases emits with isSlot | isNominals | ⟨nonempty, _⟩
      · exact absurd isSlot (by simp)
      · exact absurd isNominals (by simp)
      · intro same
        have lengths := congrArg List.length step.producesPending
        rw [← same, List.length_append] at lengths
        exact nonempty (List.eq_nil_of_length_eq_zero (by omega))
    | restart _ _ _ emitted _ step =>
      rcases emits with isSlot | isNominals | ⟨nonempty, _⟩
      · exact absurd isSlot (by simp)
      · exact absurd isNominals (by simp)
      · intro same
        have lengths := congrArg List.length step.producesPending
        rw [← same, List.length_append] at lengths
        exact nonempty (List.eq_nil_of_length_eq_zero (by omega))
    | _ => exact absurd emits (by simp [NetworkTransition.Emits, NetworkTransition.scope])
  · intro moved
    exact Classical.byContradiction
      (fun silent => moved (transition.touchesOnly .pending silent))

/-- So the trace before a step is a prefix of the trace after it. -/
theorem observations_prefix {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    before.observations <+: after.observations := by
  obtain ⟨emitted, appended⟩ := observations_extend transition
  exact ⟨emitted, appended.symm⟩

/-- And across a whole execution, by the same argument. -/
theorem execution_observations_extend {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    ∃ emitted, after.observations = before.observations ++ emitted := by
  induction execution with
  | still => exact ⟨[], (List.append_nil _).symm⟩
  | more _ step ih =>
    obtain ⟨earlier, upToHere⟩ := ih
    obtain ⟨segment, lastStep⟩ := observations_extend step.transition
    exact ⟨earlier ++ segment, by rw [lastStep, upToHere, List.append_assoc]⟩

/--
**No execution retracts an observation.**

The form a specification consumes: whatever the schedule did, everything
observed so far is still observed. `docs/FOUNDATION.md` law 7 at the trace — an
obligation discharged by emitting an observation cannot be undischarged by a
later step.
-/
theorem execution_observations_prefix {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    before.observations <+: after.observations := by
  obtain ⟨emitted, appended⟩ := execution_observations_extend execution
  exact ⟨emitted, appended.symm⟩

/-! ## What a run has produced -/

/--
**The produced trace only ever grows, and a commit does not change it.**

`LogicalProcessNetworkCore.produced` is `observations ++ pending`: everything the
program has said, published or not. Every constructor either produces into
`pending` — `processStep`, `spawn`, `restart` — or moves a prefix from `pending`
to `observations`, which is `commit` and leaves the concatenation alone, or
touches neither.

This is the law `docs/PROCESS_IMPLEMENTATION_PLAN.md` §10.66 asks for, and the
reason it could not be a field: nothing about a single *world* says its `pending`
was produced by anything, because a world is a record and its `pending` can be
any list. What is true is about *executions*, and this is the one-step form of
it.

Its payoff is `commit_publishes_only_what_the_run_produced` below: a commit
appends to `observations` from `pending`, `produced` never shrinks, and so
everything a run has committed at any point is part of what it produced starting
from wherever it started.
-/
theorem produced_extends {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    ∃ emitted, after.produced = before.produced ++ emitted := by
  by_cases emits : transition.Emits
  · cases transition with
    | processStep _ _ _ emitted _ _ step =>
      refine ⟨emitted, ?_⟩
      show after.observations ++ after.pending = before.observations ++ before.pending ++ emitted
      rw [step.producesPending, ← step.scope .observations (by simp), List.append_assoc]
    | spawn _ _ _ emitted _ step =>
      refine ⟨emitted, ?_⟩
      show after.observations ++ after.pending = before.observations ++ before.pending ++ emitted
      rw [step.producesPending, ← step.scope .observations (by simp), List.append_assoc]
    | restart _ _ _ emitted _ step =>
      refine ⟨emitted, ?_⟩
      show after.observations ++ after.pending = before.observations ++ before.pending ++ emitted
      rw [step.producesPending, ← step.scope .observations (by simp), List.append_assoc]
    | commit emitted step =>
      refine ⟨[], ?_⟩
      show after.observations ++ after.pending = before.observations ++ before.pending ++ []
      rw [step.appended, step.earned, List.append_nil, List.append_assoc]
    | _ => exact absurd emits (by simp [NetworkTransition.Emits, NetworkTransition.scope])
  · refine ⟨[], ?_⟩
    have samePending := transition.touchesOnly .pending emits
    have sameObservations := trace_unchanged_of_silent transition emits
    show after.observations ++ after.pending = before.observations ++ before.pending ++ []
    rw [← samePending, ← sameObservations, List.append_nil]

/--
**A commit changes nothing about what has been produced.**

The half of `produced_extends` worth naming on its own: publishing is a move
across the boundary between the two traces, not an addition to either side's
total. It is what makes `produced` the right thing to state a growth law about —
a law about `observations` alone would be satisfied by a plan that never
commits, and a law about `pending` alone is false, because a commit shrinks it.
-/
theorem commit_preserves_produced {before after : plan.LogicalProcessNetwork}
    {emitted : Trace boundary.Observation} (step : plan.Commits before after emitted) :
    after.produced = before.produced := by
  show after.observations ++ after.pending = before.observations ++ before.pending
  rw [step.appended, step.earned, List.append_assoc]

/-- **And across a whole execution**, by the same argument. -/
theorem execution_produced_extends {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    ∃ emitted, after.produced = before.produced ++ emitted := by
  induction execution with
  | still => exact ⟨[], (List.append_nil _).symm⟩
  | more _ step ih =>
    obtain ⟨earlier, upToHere⟩ := ih
    obtain ⟨segment, lastStep⟩ := produced_extends step.transition
    exact ⟨earlier ++ segment, by rw [lastStep, upToHere, List.append_assoc]⟩

/--
**So a run publishes nothing it did not produce.**

`docs/PROCESS_IMPLEMENTATION_PLAN.md` §10.66's claim, at the layer it belongs to.
`Commits.earned` says a commit publishes what is *pending*; this says what is
pending was produced by the run rather than being a value in a record. Together
they are the provenance the commit transition had none of before
`NetworkFragment.pending` existed — when a commit of an arbitrary observation was
a legal step of every network, which made
`Grass/Process/Network/Progress.lean`'s `AtFrontier` empty for every measure.

Note what it is relative to: whatever the execution started from. A run begun at
an `ExactInitialNetwork` starts with `observations = []` and `pending` the root's
projected start emission, so there the produced trace is exactly what the run
emitted; a run begun anywhere else inherits whatever that world claimed.
`Grass/Process/Network/Progress.lean`'s `startIsInitial` is what ties a progress
claim to the first case.
-/
theorem commit_publishes_only_what_the_run_produced
    {start network : plan.LogicalProcessNetwork} (execution : plan.StepsTo start network) :
    ∃ emitted, network.produced = start.produced ++ emitted ∧
      network.observations <+: start.produced ++ emitted := by
  obtain ⟨emitted, grew⟩ := execution_produced_extends execution
  exact ⟨emitted, grew, grew ▸ network.observations_prefix_produced⟩

/-! ## What independence buys at the trace -/

/--
**Two independent steps cannot both emit.**

The Mazurkiewicz content of `docs/PROCESS.md` §7, and it costs one line because
of a fact nothing arranged for it: every observation-touching constructor
declares `.pending` in its scope, and `NetworkTransition.Independent` is scope
disjointness.

So a swap of two independent steps cannot reorder two emissions — there are
never two emissions to reorder. §7's `BoundaryObservationsCommute` has no
content to prove at this layer, which is a stronger outcome than proving it.
-/
theorem independent_steps_do_not_both_emit
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right) : ¬ (left.Emits ∧ right.Emits) :=
  fun both => independent .pending both.1 both.2

/--
**So one of any two independent steps leaves the trace exactly.**

The usable form: whichever way the scheduler ran them, at most one contributed,
and the other's endpoints agree on the trace.
-/
theorem one_of_two_independent_steps_is_silent
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right) :
    a.observations = b.observations ∨ c.observations = d.observations := by
  by_cases emits : left.Emits
  · exact Or.inr (trace_unchanged_of_silent right
      (fun inRight => independent .pending emits inRight))
  · exact Or.inl (trace_unchanged_of_silent left emits)

/--
**An emission is attributable to one step.**

If a step emitted anything at all, every step independent of it emitted nothing.
That is what makes a trace segment a fact about *which* step ran rather than
about the schedule: two independent steps never compete for a position in the
trace.
-/
theorem emission_is_attributable
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right)
    (emitted : a.observations ≠ b.observations) :
    c.observations = d.observations := by
  refine trace_unchanged_of_silent right (fun inRight => ?_)
  refine emitted (trace_unchanged_of_silent left (fun inLeft => ?_))
  exact independent .pending inLeft inRight

/--
**A swap moves the emission from one side of the schedule to the other, and
changes nothing else about the trace.**

Both orders run two independent steps, so in each order one of them is silent
and the intermediate state's trace is either the start's or the end's. There is
no third possibility, and in particular no order in which the trace is built up
in two pieces — which is what a commutation argument about observation segments
would have had to rule out, and what
`independent_steps_do_not_both_emit` rules out instead.

The swap is what supplies the reordered execution's intermediate state, and the
existential carries the two reordered *steps* and their scope equations so that
`middle` is pinned to the swap's own witness. That matters: a version whose
existential mentioned only `middle` is satisfied by `⟨first, Or.inl rfl⟩` with
no independence, no swap and no steps at all. Two earlier drafts were vacuous in
two different ways — the first took the swap hypothesis and never used it, and
the second destructured it but concluded something the swap did not bound. Local
adversarial review found both.
-/
theorem a_swap_only_moves_the_emission
    {first second third : plan.LogicalProcessNetwork}
    {left : plan.NetworkStep first second} {right : plan.NetworkStep second third}
    (independent : left.transition.Independent right.transition)
    (swap : SwapsWith left right) :
    (first.observations = second.observations ∨ second.observations = third.observations) ∧
      ∃ (middle : plan.LogicalProcessNetwork)
        (swappedRight : plan.NetworkStep first middle)
        (swappedLeft : plan.NetworkStep middle third),
        (∀ fragment, swappedRight.transition.scope fragment ↔ right.transition.scope fragment) ∧
        (∀ fragment, swappedLeft.transition.scope fragment ↔ left.transition.scope fragment) ∧
        (first.observations = middle.observations ∨
          middle.observations = third.observations) := by
  refine ⟨one_of_two_independent_steps_is_silent independent, ?_⟩
  obtain ⟨middle, swappedRight, swappedLeft, rightScope, leftScope⟩ := swap
  refine ⟨middle, swappedRight, swappedLeft, rightScope, leftScope, ?_⟩
  refine one_of_two_independent_steps_is_silent (left := swappedRight.transition)
    (right := swappedLeft.transition) ?_
  intro fragment inSwappedRight inSwappedLeft
  exact independent fragment ((leftScope fragment).mp inSwappedLeft)
    ((rightScope fragment).mp inSwappedRight)

end ProcessPlan

end Grass.Process
