import Grass.Process.Trace.Independence

/-!
# What the observation trace can and cannot witness

`docs/PROCESS.md` §7 asks for the graph-level result the flattening and
serial-scheduler theorems consume:

> The trace congruence is generated by adjacent independent swaps (a nominal
> partial-order/Mazurkiewicz trace), preserving dependent result and occurrence
> identity through each transport.

`Grass/Process/Trace/Independence.lean` says when two steps are independent and
names the diamond as an obligation rather than assuming it. This module is the
other half: what the *trace* does across a schedule, which turns out to be
answerable without the diamond.

## The two theorems that matter

**The trace only grows.** `observations_extend` is by cases over all
twenty-three constructors of `NetworkTransition`, and it is the reason a
specification stated over observations is stable under execution: no step
rewrites or truncates the trace, so an observation a specification demanded
cannot be dropped by a later step. Twenty-one constructors get it from
`touchesOnly` — they do not scope the trace at all — and the two that do,
`processStep` and `commit`, carry an append equation as a field.

**Two independent steps cannot both emit.** `independent_steps_do_not_both_emit`
is a one-line consequence of a fact that was not arranged for it: both emitting
constructors declare `.observations` in their scope, and `Independent` is scope
disjointness. So of any two independent steps, at least one leaves the trace
exactly as it found it.

That is the Mazurkiewicz content in the form this layer can support. Swapping
two independent steps cannot reorder two emissions, because there are never two
emissions to reorder — the schedule between independent steps is unobservable
through the trace *by construction*, not by a commutation argument about
segments.

## What is still owed, and where

The constructive diamond stays where `Independence.lean` left it. What this
module shows is that the diamond is the *whole* remaining obligation for the
trace: `a_swap_only_moves_the_emission` needs a swap for the reordered
execution's intermediate state and needs nothing else. A reader tempted to add a
separate "observations commute" lemma — §7's `BoundaryObservationsCommute` —
should note that at this layer it would have no content to prove.
-/

namespace Grass.Process

open Grass.Specification

universe u w v r m o

namespace ProcessPlan

variable {registry : ProtocolRegistry.{u, w, v}} {boundary : DriverBoundary.{u}}
  {Obligations : Type o} {plan : ProcessPlan.{u, w, v, r, m, o} registry boundary Obligations}

/-! ## Who may write the trace -/

/--
A step that may append to the observation trace.

Not a new field: it is `.observations` being in the step's declared scope, so a
step emits exactly when it said it might.
-/
def NetworkTransition.Emits {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) : Prop :=
  transition.scope .observations

/--
A step that did not declare the trace left it exactly.

Immediate from `touchesOnly`, and the half of the argument that covers
twenty-one of the twenty-three constructors.
-/
theorem trace_unchanged_of_silent {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) (silent : ¬ transition.Emits) :
    before.observations = after.observations :=
  transition.touchesOnly .observations silent

/--
**The observation trace only ever grows.**

`docs/PROCESS.md` §6 says a commit "appends to the observation trace", and this
is what that is worth once the whole transition family is in view: *no* step
rewrites or truncates it. A specification stated over observations is therefore
stable under execution — an observation it demanded cannot be dropped by a later
step, whatever that step was.

The proof is a case split on whether the step declared the trace at all. If it
did not, `touchesOnly` gives equality. If it did, it is one of exactly two
constructors, and each carries the append equation as a field: `processStep`'s
`observationsExtend` and `commit`'s `appended`.

Worth noting what would have gone wrong without the scope discipline. There is
nothing in `LogicalProcessNetworkCore` that stops a transition from setting
`observations` to `[]`; what stops it is that such a step would have to declare
`.observations` in its scope, and then it would have to be one of these two
constructors, and both of them append.
-/
theorem observations_extend {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    ∃ emitted, after.observations = before.observations ++ emitted := by
  by_cases emits : transition.Emits
  · cases transition with
    | processStep _ _ _ _ step => exact step.observationsExtend
    | commit emitted step => exact ⟨emitted, step.appended⟩
    | _ => exact absurd emits (by simp [NetworkTransition.Emits, NetworkTransition.scope])
  · exact ⟨[], by rw [← trace_unchanged_of_silent transition emits, List.append_nil]⟩

/-- So the trace before a step is a prefix of the trace after it. -/
theorem observations_prefix {before after : plan.LogicalProcessNetwork}
    (transition : plan.NetworkTransition before after) :
    before.observations <+: after.observations := by
  obtain ⟨emitted, appended⟩ := observations_extend transition
  exact ⟨emitted, appended.symm⟩

/-- And across a whole execution, by the same argument. -/
theorem execution_observations_extend {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    ∃ emitted, after.observations = before.observations ++ emitted := by
  induction execution with
  | still => exact ⟨[], (List.append_nil _).symm⟩
  | more _ step ih =>
    obtain ⟨earlier, upToHere⟩ := ih
    obtain ⟨segment, lastStep⟩ := observations_extend step.transition
    exact ⟨earlier ++ segment, by rw [lastStep, upToHere, List.append_assoc]⟩

/--
**No execution retracts an observation.**

The form a specification consumes: whatever the schedule did, everything
observed so far is still observed. `docs/FOUNDATION.md` law 7 at the trace — an
obligation discharged by emitting an observation cannot be undischarged by a
later step.
-/
theorem execution_observations_prefix {before after : plan.LogicalProcessNetwork}
    (execution : plan.StepsTo before after) :
    before.observations <+: after.observations := by
  obtain ⟨emitted, appended⟩ := execution_observations_extend execution
  exact ⟨emitted, appended.symm⟩

/-! ## What independence buys at the trace -/

/--
**Two independent steps cannot both emit.**

The Mazurkiewicz content of `docs/PROCESS.md` §7, and it costs one line because
of a fact nothing arranged for it: both emitting constructors declare
`.observations` in their scope, and `NetworkTransition.Independent` is scope
disjointness.

So a swap of two independent steps cannot reorder two emissions — there are
never two emissions to reorder. §7's `BoundaryObservationsCommute` has no
content to prove at this layer, which is a stronger outcome than proving it.
-/
theorem independent_steps_do_not_both_emit
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right) : ¬ (left.Emits ∧ right.Emits) :=
  fun both => independent .observations both.1 both.2

/--
**So one of any two independent steps leaves the trace exactly.**

The usable form: whichever way the scheduler ran them, at most one contributed,
and the other's endpoints agree on the trace.
-/
theorem one_of_two_independent_steps_is_silent
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right) :
    a.observations = b.observations ∨ c.observations = d.observations := by
  by_cases emits : left.Emits
  · exact Or.inr (trace_unchanged_of_silent right
      (fun inRight => independent .observations emits inRight))
  · exact Or.inl (trace_unchanged_of_silent left emits)

/--
**An emission is attributable to one step.**

If a step emitted anything at all, every step independent of it emitted nothing.
That is what makes a trace segment a fact about *which* step ran rather than
about the schedule: two independent steps never compete for a position in the
trace.
-/
theorem emission_is_attributable
    {a b c d : plan.LogicalProcessNetwork}
    {left : plan.NetworkTransition a b} {right : plan.NetworkTransition c d}
    (independent : left.Independent right)
    (emitted : a.observations ≠ b.observations) :
    c.observations = d.observations := by
  refine trace_unchanged_of_silent right (fun inRight => ?_)
  refine emitted (trace_unchanged_of_silent left (fun inLeft => ?_))
  exact independent .observations inLeft inRight

/--
**A swap moves the emission from one side of the schedule to the other, and
changes nothing else about the trace.**

Both orders run two independent steps, so in each order one of them is silent
and the intermediate state's trace is either the start's or the end's. There is
no third possibility, and in particular no order in which the trace is built up
in two pieces — which is what a commutation argument about observation segments
would have had to rule out, and what
`independent_steps_do_not_both_emit` rules out instead.

The swap is what supplies the reordered execution's intermediate state, so this
says something about *both* orders rather than about one; the scope equations in
`SwapsWith` are what carry independence across to the reordered pair. An earlier
draft of this theorem stated only that the reordered execution emitted some
segment, which is true of any two-step execution and mentions the swap nowhere —
the unused-variable linter did not catch it, because the hypothesis had been
named `_swap`.
-/
theorem a_swap_only_moves_the_emission
    {first second third : plan.LogicalProcessNetwork}
    {left : plan.NetworkStep first second} {right : plan.NetworkStep second third}
    (independent : left.transition.Independent right.transition)
    (swap : SwapsWith left right) :
    (first.observations = second.observations ∨ second.observations = third.observations) ∧
      ∃ middle : plan.LogicalProcessNetwork,
        first.observations = middle.observations ∨ middle.observations = third.observations := by
  refine ⟨one_of_two_independent_steps_is_silent independent, ?_⟩
  obtain ⟨middle, swappedRight, swappedLeft, rightScope, leftScope⟩ := swap
  refine ⟨middle, one_of_two_independent_steps_is_silent (left := swappedRight.transition)
    (right := swappedLeft.transition) ?_⟩
  intro fragment inSwappedRight inSwappedLeft
  exact independent fragment ((leftScope fragment).mp inSwappedLeft)
    ((rightScope fragment).mp inSwappedRight)

end ProcessPlan

end Grass.Process
