import Spikes.«5_Spinning_Cube».Process

namespace Grass.Spikes.SpinningCube

def instanceExtensionNames : Vec CString := #[
  "VK_KHR_surface",
  "VK_KHR_win32_surface"
]

def deviceExtensionNames : Vec CString := #["VK_KHR_swapchain"]

def instanceFunctionNames : Vec CString := #[
  "vkDestroyInstance",
  "vkCreateWin32SurfaceKHR",
  "vkDestroySurfaceKHR",
  "vkEnumeratePhysicalDevices",
  "vkGetPhysicalDeviceProperties2",
  "vkGetPhysicalDeviceFeatures2",
  "vkEnumerateDeviceExtensionProperties",
  "vkGetPhysicalDeviceQueueFamilyProperties2",
  "vkGetPhysicalDeviceSurfaceSupportKHR",
  "vkGetPhysicalDeviceSurfaceCapabilitiesKHR",
  "vkGetPhysicalDeviceSurfaceFormatsKHR",
  "vkCreateDevice"
]

def deviceFunctionNames : Vec CString := #[
  "vkDestroyDevice",
  "vkGetDeviceQueue",
  "vkCreateCommandPool",
  "vkDestroyCommandPool",
  "vkAllocateCommandBuffers",
  "vkCreateSemaphore",
  "vkDestroySemaphore",
  "vkCreateFence",
  "vkDestroyFence",
  "vkCreateShaderModule",
  "vkDestroyShaderModule",
  "vkCreatePipelineLayout",
  "vkDestroyPipelineLayout",
  "vkCreateSwapchainKHR",
  "vkDestroySwapchainKHR",
  "vkGetSwapchainImagesKHR",
  "vkCreateImageView",
  "vkDestroyImageView",
  "vkCreateGraphicsPipelines",
  "vkDestroyPipeline",
  "vkDeviceWaitIdle",
  "vkWaitForFences",
  "vkAcquireNextImageKHR",
  "vkResetFences",
  "vkResetCommandBuffer",
  "vkBeginCommandBuffer",
  "vkCmdPipelineBarrier2",
  "vkCmdBeginRendering",
  "vkCmdBindPipeline",
  "vkCmdSetViewport",
  "vkCmdSetScissor",
  "vkCmdPushConstants",
  "vkCmdDraw",
  "vkCmdEndRendering",
  "vkEndCommandBuffer",
  "vkQueueSubmit2",
  "vkQueuePresentKHR"
]

def cubeFrameObjects : Vec StackObjectSpec := #[
  .object `wc .wndClassExW,
  .object `msg .msg,
  .object `state .cubeWindowState,
  .object `qpcFrequency .int64,
  .object `qpcEpoch .int64,
  .object `qpcPrevious .int64,
  .object `qpcNow .int64,
  .object `processHeap .pointer,
  .object `vkCreateInstancePtr .pointer,
  .object `instance .vkInstance,
  .object `surface .vkSurfaceKHR,
  .object `physical .vkPhysicalDevice,
  .object `qfamily .uint32,
  .object `device .vkDevice,
  .object `queue .vkQueue,
  .object `commandPool .vkCommandPool,
  .object `cmd .vkCommandBuffer,
  .object `imageAvail .vkSemaphore,
  .object `renderDone .vkSemaphore,
  .object `fence .vkFence,
  .object `vertModule .vkShaderModule,
  .object `fragModule .vkShaderModule,
  .object `pipelineLayout .vkPipelineLayout,
  .object `pipeline .vkPipeline,
  .object `swapchain .vkSwapchainKHR,
  .object `oldSwapchain .vkSwapchainKHR,
  .object `newSwapchain .vkSwapchainKHR,
  .object `count .uint32,
  .object `deviceCount .uint32,
  .object `devices .pointer,
  .object `extCount .uint32,
  .object `extProps .pointer,
  .object `queueCount .uint32,
  .object `queueProps .pointer,
  .object `supported .vkBool32,
  .object `fmtCount .uint32,
  .object `formats .pointer,
  .object `surfaceFormat .vkSurfaceFormatKHR,
  .object `imageCount .uint32,
  .object `images .pointer,
  .object `views .pointer,
  .object `imageInitialized .pointer,
  .object `initializedViewCount .uint32,
  .object `viewIndex .uint32,
  .object `imageIndex .uint32,
  .object `appInfo .vkApplicationInfo,
  .object `instanceCI .vkInstanceCreateInfo,
  .object `properties2 .vkPhysicalDeviceProperties2,
  .object `queueCI .vkDeviceQueueCreateInfo,
  .object `features2 .vkPhysicalDeviceFeatures2,
  .object `features13 .vkPhysicalDeviceVulkan13Features,
  .object `deviceCI .vkDeviceCreateInfo,
  .object `win32SurfaceCI .vkWin32SurfaceCreateInfoKHR,
  .object `commandPoolCI .vkCommandPoolCreateInfo,
  .object `commandBufferAI .vkCommandBufferAllocateInfo,
  .object `semaphoreCI .vkSemaphoreCreateInfo,
  .object `fenceCI .vkFenceCreateInfo,
  .object `vertexShaderCI .vkShaderModuleCreateInfo,
  .object `fragmentShaderCI .vkShaderModuleCreateInfo,
  .object `pipelineLayoutCI .vkPipelineLayoutCreateInfo,
  .object `pushConstantRange .vkPushConstantRange,
  .object `caps .vkSurfaceCapabilitiesKHR,
  .object `extent .vkExtent2D,
  .object `swapCI .vkSwapchainCreateInfoKHR,
  .object `pipelineRendering .vkPipelineRenderingCreateInfo,
  .object `graphicsCI .vkGraphicsPipelineCreateInfo,
  .object `imageViewCI .vkImageViewCreateInfo,
  .object `commandBufferBI .vkCommandBufferBeginInfo,
  .object `shaderStages (.array 2 .vkPipelineShaderStageCreateInfo),
  .object `emptyVertexInput .vkPipelineVertexInputStateCreateInfo,
  .object `lineList .vkPipelineInputAssemblyStateCreateInfo,
  .object `oneDynamicViewport .vkPipelineViewportStateCreateInfo,
  .object `lineRaster .vkPipelineRasterizationStateCreateInfo,
  .object `sample1 .vkPipelineMultisampleStateCreateInfo,
  .object `colorAttachment .vkPipelineColorBlendAttachmentState,
  .object `opaqueBlend .vkPipelineColorBlendStateCreateInfo,
  .object `dynamicStates (.array 2 .vkDynamicState),
  .object `viewportScissor .vkPipelineDynamicStateCreateInfo,
  .object `push .cubePushConstants,
  .object `barrier .vkImageMemoryBarrier2,
  .object `dependencyInfo .vkDependencyInfo,
  .object `rendering .vkRenderingInfo,
  .object `renderingAttachment .vkRenderingAttachmentInfo,
  .object `viewport .vkViewport,
  .object `scissor .vkRect2D,
  .object `submit .vkSubmitInfo2,
  .object `waitSemaphoreInfo .vkSemaphoreSubmitInfo,
  .object `signalSemaphoreInfo .vkSemaphoreSubmitInfo,
  .object `commandBufferInfo .vkCommandBufferSubmitInfo,
  .object `present .vkPresentInfoKHR,
  .object `instanceDispatch (.array instanceFunctionNames.size .pointer),
  .object `deviceDispatch (.array deviceFunctionNames.size .pointer),
  .object `deviceDispatchCandidate (.array deviceFunctionNames.size .pointer),
  .object `vkDestroyDevicePtr .pointer,
  .object `ownership .cubeOwnershipLedger,
  .outgoingCallArea,
  .parallelMoveSpill
]

def cubeCallbackFrameObjects : Vec StackObjectSpec := #[
  .object `callbackHwnd .pointer,
  .object `callbackMessage .uint32,
  .object `callbackWparam .uint64,
  .object `callbackLparam .int64,
  .object `callbackState .pointer,
  .outgoingCallArea,
  .parallelMoveSpill
]

def cubeFrameLayout : StackFrameLayout :=
  StackFrameLayout.packWin64 cubeFrameObjects

def cubeCallbackFrameLayout : StackFrameLayout :=
  StackFrameLayout.packWin64 cubeCallbackFrameObjects

end Grass.Spikes.SpinningCube
