//! Common records shared across event kinds (AGENT_BUS_SCHEMA.md section 3).

use crate::events::Role;
use crate::scalars::{Agent, CoordinationTopic, EventId, Short, StringSet, Text};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(deny_unknown_fields)]
pub struct DependencyImport {
    pub agent: Agent,
    pub interface: Short,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PlanStepState {
    Pending,
    Active,
    Done,
    Dropped,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlanStep {
    pub id: Short,
    pub state: PlanStepState,
    pub text: Text,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum Priority {
    Critical,
    High,
    Normal,
    Low,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Finding {
    pub id: Short,
    pub priority: Priority,
    pub locations: Vec<Text>,
    pub rationale: Text,
    pub closure_conditions: Text,
}

/// A finding's global identity is `(changes_event, finding_id)` -- the id
/// alone is only unique within one `review.changes_requested`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(deny_unknown_fields)]
pub struct FindingRef {
    pub changes_event: EventId,
    pub finding_id: Short,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum FindingDispositionKind {
    Cleared,
    Superseded,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FindingDisposition {
    pub changes_event: EventId,
    pub finding_id: Short,
    pub disposition: FindingDispositionKind,
    pub rationale: Text,
}

/// Occurs only inside `review.merge_authorized`, so `Passed` is its sole
/// variant: a failed check is reported through `progress.reported` (and
/// normally produces `review.changes_requested`) rather than appearing here.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CheckOutcome {
    Passed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CheckResult {
    pub command: Text,
    pub result: CheckOutcome,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Text>,
}

/// docs/AGENT_COORDINATION_EVOLUTION.md section 3.1's `FrictionReport.impact`
/// vocabulary. Kebab-case to match the doc's own hyphenated spelling
/// (`proof-fragility`, `false-positive`, `missing-abstraction`) rather than
/// the crate's usual snake_case.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum Impact {
    Latency,
    Ceremony,
    ProofFragility,
    Rebuild,
    Discoverability,
    Coordination,
    FalsePositive,
    MissingAbstraction,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Frequency {
    Once,
    Recurring,
    Pervasive,
}

/// One quantitative datum backing a friction report -- section 3.1 names
/// wall time, retry count, commands needed, declarations rechecked, proof
/// lines, and generated bytes as examples without fixing a schema for them;
/// `metric` names which of those (or another) this is, `value` is its
/// count/duration in whatever unit `metric` implies, and `unit` disambiguates
/// when it isn't obvious from `metric` alone.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Measurement {
    pub metric: Short,
    pub value: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit: Option<Short>,
}

/// docs/AGENT_COORDINATION_EVOLUTION.md section 3.3's five synthesis
/// dispositions.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FrictionDispositionKind {
    Promoted,
    AcceptedCost,
    Duplicate,
    NeedsEvidence,
    Deferred,
}

// -------------------------------------------------------------- broadcasts

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Importance {
    Informational,
    Elevated,
    Critical,
}

/// docs/AGENT_COORDINATION_EVOLUTION.md section 4.1's `acknowledgement:
/// none | required`.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AckRequirement {
    None,
    Required,
}

/// Who a broadcast addresses, before resolution fixes it into a concrete
/// `audience_snapshot` (section 4.2). Each variant is exactly one of the
/// selector shapes the doc names: "an audience selector may name agents,
/// roles, topic subscribers, dependents of an interface, or all active
/// agents."
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case", tag = "kind", content = "value")]
pub enum AudienceSelector {
    Agents(StringSet<Agent>),
    Roles(std::collections::BTreeSet<Role>),
    TopicSubscribers(CoordinationTopic),
    InterfaceDependents(Short),
    AllActive,
}
