import Grass.Process.Network.Boundary

/-!
# The sequential authoring surface

`docs/PROCESS.md` §4:

> The ordinary authoring interface is a typed sequential effect machine.
> Custom headers, multi-pass algorithms, retry policy, and custom error handling
> normally change `State` and `decide`; they do not require an actor graph or
> bag equations.

This module is that interface and nothing else. A Hello World author writes a
`SequentialMachine`; the process graph, the occurrence identities, the channels,
and the escrow are generated by the adapter and are never authored. That is
`docs/FOUNDATION.md` law 17: "serial authoring may synthesize a degenerate
process realization, but it may not introduce an alternate semantics or theorem
route."

The adapter itself — `SequentialAdapter.elaborateMachine` and the transport of
`SequentialMachineRealizes` to `DirectProgramRealizes` — is deliberately not
here. It needs the occurrence and child-binding machinery, and
`docs/PROCESS_IMPLEMENTATION_PLAN.md` schedules it with the rest of the proof
package. What is here is what an author writes, which by §1 of that plan must be
frozen first.

## The one theorem this module owes

A sequential machine can spin: `decide` may return `internal` forever. That is
exactly the failure `docs/PROCESS.md` §7 excludes with "reach a law-bearing
external/demand-result frontier in finite internal work", and at this layer —
unlike at the `ProcessSpec` layer, where every transition consumes an event —
the clause has real content, because an `internal` decision is a genuine
internal step.

`reachesFrontier` below is that theorem, proved once from the machine's own
rank. An author supplies a well-founded rank that internal decisions decrease;
they do not prove anything about frontiers.
-/

namespace Grass.Process

universe u

/--
What a sequential machine does at one state.

`effect`'s continuation is indexed by the exact result of the exact demand it
issued. That dependency is what makes the adapter's job structural:
`docs/PROCESS.md` §4 notes that "because a sequential decision has at most one
newly issued effect and its continuation is indexed by that exact effect's
result, occurrence identity, pending multiplicity, child binding, and terminal
disposition are generated structurally."
-/
inductive SequentialDecision (boundary : DriverBoundary.{u})
    (State Terminal : Type u) : Type u
  /-- Move to a new state, emitting a finite observation segment. -/
  | internal (next : State) (observations : ObservationSegment boundary.Observation)
  /-- Issue one demand and continue with its result. -/
  | effect (demand : boundary.Demand) (resume : boundary.Result demand → State)
  /-- Finish. -/
  | terminal (result : Terminal)

namespace SequentialDecision

variable {boundary : DriverBoundary.{u}} {State Terminal : Type u}

/--
A decision is at a frontier when the machine cannot proceed on its own: it has
asked the environment for something, or it has finished.
-/
def AtFrontier : SequentialDecision boundary State Terminal → Prop
  | .internal _ _ => False
  | .effect _ _ => True
  | .terminal _ => True

@[simp] theorem not_atFrontier_internal (next : State)
    (observations : ObservationSegment boundary.Observation) :
    ¬ (SequentialDecision.internal (Terminal := Terminal) next observations).AtFrontier :=
  id

@[simp] theorem atFrontier_effect (demand : boundary.Demand)
    (resume : boundary.Result demand → State) :
    (SequentialDecision.effect (Terminal := Terminal) demand resume).AtFrontier :=
  trivial

@[simp] theorem atFrontier_terminal (result : Terminal) :
    (SequentialDecision.terminal (boundary := boundary) (State := State) result).AtFrontier :=
  trivial

end SequentialDecision

/--
A typed sequential effect machine.

The invariant fields are the author's correctness obligation and the rank fields
are the author's progress obligation. Nothing else is required: no process
kinds, no channels, no population, no escrow.
-/
structure SequentialMachine (boundary : DriverBoundary.{u}) : Type (u + 1) where
  /-- The machine's own state. -/
  State : Type u
  /-- The parameter it is started with. -/
  Request : Type u
  /-- The value it finishes with. -/
  Terminal : Type u
  /-- The starting state for a request. -/
  initial : Request → State
  /-- What to do at a state. -/
  decide : State → SequentialDecision boundary State Terminal
  /-- The author's state invariant. -/
  invariant : State → Prop
  /-- Every start satisfies it. -/
  initialInvariant : ∀ request, invariant (initial request)
  /-- Internal decisions preserve it. -/
  internalPreserves : ∀ state next observations,
    decide state = .internal next observations → invariant state → invariant next
  /--
  Every permitted result of an issued effect preserves it.

  Quantified over *every* result of the exact demand, which is
  `docs/FOUNDATION.md` law 5: an author cannot handle the success case and leave
  the failure case to a later proof, because the continuation is total on the
  demand's dependent result type.
  -/
  effectResumes : ∀ state demand resume,
    decide state = .effect demand resume → invariant state →
    ∀ result, invariant (resume result)
  /-- The carrier of the internal measure. -/
  Rank : Type u
  /-- Its strict order. -/
  rankLt : Rank → Rank → Prop
  /-- No infinite internal descent. -/
  rankWellFounded : WellFounded rankLt
  /-- The measure. -/
  rank : State → Rank
  /--
  Internal decisions strictly decrease the measure.

  This is the entire progress obligation of a sequential author, and
  `reachesFrontier` is what it buys.
  -/
  internalDecreases : ∀ state next observations,
    decide state = .internal next observations → rankLt (rank next) (rank state)

namespace SequentialMachine

variable {boundary : DriverBoundary.{u}} (machine : SequentialMachine boundary)

/-- One internal step. -/
def InternalStep (before after : machine.State) : Prop :=
  ∃ observations, machine.decide before = .internal after observations

/-- Zero or more internal steps. -/
inductive InternalSteps (machine : SequentialMachine boundary) :
    machine.State → machine.State → Prop
  | refl (state : machine.State) : InternalSteps machine state state
  | step {start middle finish : machine.State}
      (first : machine.InternalStep start middle)
      (rest : InternalSteps machine middle finish) :
      InternalSteps machine start finish

/--
**Finite internal work between frontiers.** From any state, finitely many
internal steps reach a decision that is at a frontier.

This is the sequential form of the second disjunct of `docs/PROCESS.md` §7. It
is proved once, here, by well-founded recursion on the author's rank; an author
who supplies `internalDecreases` never states or proves it.
-/
theorem reachesFrontier (state : machine.State) :
    ∃ frontier, machine.InternalSteps state frontier ∧
      (machine.decide frontier).AtFrontier := by
  induction hypothesis : machine.rank state using
      machine.rankWellFounded.induction generalizing state with
  | _ current ih =>
    match decision : machine.decide state with
    | .internal next observations =>
      obtain ⟨frontier, steps, atFrontier⟩ :=
        ih (machine.rank next)
          (hypothesis ▸ machine.internalDecreases state next observations decision)
          next rfl
      exact ⟨frontier, .step ⟨observations, decision⟩ steps, atFrontier⟩
    | .effect demand resume =>
      exact ⟨state, .refl state, by rw [decision]; exact trivial⟩
    | .terminal result =>
      exact ⟨state, .refl state, by rw [decision]; exact trivial⟩

/--
A machine whose decision at a state is internal is not at a frontier, and
conversely.

Trivial, but it is the fact a driver's dispatch loop branches on, and stating it
keeps that loop from unfolding `AtFrontier`.
-/
theorem atFrontier_iff (state : machine.State) :
    (machine.decide state).AtFrontier ↔
      ∀ next observations, machine.decide state ≠ .internal next observations := by
  constructor
  · intro atFrontier next observations isInternal
    rw [isInternal] at atFrontier
    exact atFrontier
  · intro notInternal
    match decision : machine.decide state with
    | .internal next observations => exact absurd decision (notInternal next observations)
    | .effect _ _ => exact trivial
    | .terminal _ => exact trivial

end SequentialMachine

end Grass.Process
